[project]
name = "campaign-chronicle"
description = "A tool to support DnD session preparation for GMs and note keeping for players."
readme = "README.md"
license = { text = "MIT" }
requires-python = ">= 3.14"
dynamic = ["version"]
dependencies = [
    "typer==0.21.1",
    "flask_socketio==5.6.1"
]

[project.optional-dependencies]
dev = [
    "pre-commit>=4.0.0,<5.0.0",
    "build>=1.2.2"
]

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
version_file = "src/app/_version.py"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 80
target-version = ["py314"]
include = '\.pyi?$'
extend-exclude = '''
/(
    .github/
  | .vscode/
  | build/
  | release/
  | htmlcov/
)/
'''
skip-string-normalization = false
